server:
  port: 8888

spring:
  application:
    name: app-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yangyang0001/config.git
          search-paths: -config
      label: master

eureka:
  client:
    service-url:
      ##客户端链接注册中心的URL地址
      defaultZone: http://127.0.0.1:8100/eureka/
    ##是否注册到eureka上
    register-with-eureka: true
    ##是否需要从eureka上获取注册信息
    fetch-registry: true
    ##心跳检测检测与续约时间
    registry-fetch-interval-seconds: 30
  instance:
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2