server:
  port: 8100

spring:
    application:
      name: app-eureka

eureka:
  instance:
    ##注册中心IP地址
    hostname: 127.0.0.1
  client:
    service-url:
      ##作为客户端链接注册中心的URL地址
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    ##因为自己是为注册中心，不需要自己注册自己【集群的时候需要设置为true】
    register-with-eureka: false
    ##因为自己是为注册中心，不需要检索服务
    fetch-registry: false
  server:
    ##关闭掉eureka 的自我保护机制,无法链接 eureka-client中的服务,就将服务剔除! 2s检测一次
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
